name: "Jekyll Responsive Images"
description: "A composite action to generate responsive images for your Jekyll website using jampack tool."
author: "Lhassan Baazzi <baazzilhassan@gmail.com>"
inputs:
  path:
    description: "Path of the directory containing the static assets."
    required: false
    default: "_site/"
runs:
  using: composite
  steps:
    - name: Install latest NodeJS version
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Install jampack npm package
      shell: bash
      run: npm install -D @divriots/jampack
    - name: Genarate responsive images
      shell: bash
      run: |
        npm exec jampack ./${{ inputs.path }}
        rm -rf ./${{ inputs.path }}/_jampack
